# é necessário criar as variáveis DEPLOY_HOST, DEPLOY_KEY, NOME_ARQUIVO_PEM e NOME_ARQUIVO_JAR.
name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Atualização do código #pegando o código mais recente
      uses: actions/checkout@v2

    - name: Definindo a versão da JDK #definindo o Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # ver opções em https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
        java-version: '17' 

    - name: Build com Maven #gerando .jar na pasta target
      run: mvn -f back-end/api-learn-link/pom.xml clean package 

    - name: Gerar artefato Github com o .jar gerado
      uses: actions/upload-artifact@v4
      with:
        name: aplicacao #nome armazenado p artefato
        path: back-end/api-learn-link/target/*.jar

    - name: Gerar artefato Github com os arquivos .sh
      uses: actions/upload-artifact@v4        
      with:
        name: scripts
        path: .github/scripts/*.sh     #pegar os scripts do prof dps

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Recuperar artefato #baixa os artefatos gerados no job de build
      uses: actions/download-artifact@v4
      with:
        name: aplicacao
        path: ./

    - name: Recuperar scripts
      uses: actions/download-artifact@v4
      with:
        name: scripts
        path: ./        

    - name: Criar arquivo .pem a partir da variável DEPLOY_KEY e fazer o chmod 400 nele
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" >> $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
        chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM }}

    - name: Enviar o JAR p/ a EC2 #mudar dps c as configs da ec2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: "./*.jar"
        target: "/home/ubuntu/deploy-api/"

    - name: Enviar os Scripts p/ a EC2 #mesma coisa
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: "./*.sh"
        target: "/home/ubuntu/deploy-api/"

    - name: Conectar via SSH à EC2 privada para implantar e reiniciar a API
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} ubuntu@${{ secrets.DEPLOY_HOST }} '
          echo "${{ secrets.DEPLOY_KEY }}" > ${{ secrets.NOME_ARQUIVO_PEM }}
          chmod 400 "${{ secrets.NOME_ARQUIVO_PEM }}"
          scp -i ${{ secrets.NOME_ARQUIVO_PEM }} back/${{ secrets.NOME_ARQUIVO_JAR }} ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu
          scp -i ${{ secrets.NOME_ARQUIVO_PEM }} back/*.sh ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu
          ssh -i ${{ secrets.NOME_ARQUIVO_PEM }} ubuntu@${{ secrets.IP_PRIVADO_EC2 }} "sh /home/ubuntu/api-restart.sh"
          rm ${{ secrets.NOME_ARQUIVO_PEM }}          
        '
